all:
	ocamlfind ocamlopt \
    -w \
    -40 \
    -g \
    -o simple_agent \
    -linkall \
    -package astring \
    -package atdgen \
    -package atdgen-runtime \
    -package biniou \
    -package bytes \
    -package cohttp \
    -package cohttp-lwt \
    -package cohttp-lwt-unix \
    -package conduit \
    -package conduit-lwt \
    -package conduit-lwt-unix \
    -package easy-format \
    -package fieldslib \
    -package fmt \
    -package ipaddr \
    -package logs \
    -package lwt \
    -package magic-mime \
    -package parsexp \
    -package re \
    -package result \
    -package seq \
    -package sexplib \
    -package sexplib0 \
    -package stringext \
    -package uchar \
    -package uri \
    -package yojson \
    -package gym-http \
	-I `zeluc -where` \
    easy_format.cmxa \
    biniou.cmxa \
    yojson.cmxa \
    atdgen_runtime.cmxa \
    atdgen.cmxa \
    base64.cmxa \
    caml.cmxa \
    shadow_stdlib.cmxa \
    sexplib0.cmxa \
    base.cmxa \
    fieldslib.cmxa \
    ppx_sexp_conv_lib.cmxa \
    re.cmxa \
    re_emacs.cmxa \
    unix.cmxa \
    bigarray.cmxa \
    parsexp.cmxa \
    sexplib.cmxa \
    stringext.cmxa \
    re_posix.cmxa \
    uri.cmxa \
    cohttp.cmxa \
    result.cmxa \
    lwt.cmxa \
    cohttp_lwt.cmxa \
    astring.cmxa \
    ipaddr.cmxa \
    conduit.cmxa \
    conduit_lwt.cmxa \
    ipaddr_unix.cmxa \
    logs.cmxa \
    lwt_log.cmxa \
    lwt_unix.cmxa \
    uri_services.cmxa \
    conduit_lwt_unix.cmxa \
    fmt.cmxa \
    logs_lwt.cmxa \
    magic_mime_library.cmxa \
    cohttp_lwt_unix.cmxa \
    gym_http.cmxa \
    simple_agent.ml main.ml