# Port 5000
# Build: docker build -t rl_gym_server_001 -f Dockerfile.server .
# docker run -it -p 5000:5000 --name rl_server --privileged=true rl_gym_server_002

FROM ubuntu:16.04

COPY gym_http_server.py /server/gym_http_server.py
WORKDIR /server

RUN apt-get update && apt-get install -y \
    freeglut3-dev \
    python3-pip \
    xvfb \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install flask gym

CMD xvfb-run -s "-screen 0 1400x900x24" python3 -u gym_http_server.py --listen 0.0.0.0